### PR TITLE
Add option to verify uploaded file checksum

### PR DESCRIPTION
**Pull request by grobie**
The POST endpoint accepts now an optional `sha1` parameter. If given,
the uploaded file's SHA1 checksum is compared to that value. The file
isn't stored in case the checksums don't match and a "409 Conflict"
status code will be returned instead.

Solves #22

### CODE REVIEW

**Comment by grobie** [comment]
Instead of doing the check in the controller and calling delete afterwards, the check functionality could also be moved into the fs itself. As that would require a change of the interface, by e.g. adding a method like `CreateChecksum` which accepts an optional additional parameter, I opted for the least invasive change. Let me know what you think @xla.

**Comment by grobie** [comment]
The HTTP rfc2616 actually defines a header field [Content-MD5](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.15). It requires the implementation of a second checksum variant, but might be preferred over using a URL parameter?

**Comment by xla** [comment]
After discussing this in person @grobie and I came to the conclusion that piggy-backing on the existing standard from rfc2616 is the best way forward for now.

**Comment by xla** [comment]
This looks like it's obsolete and can be closed.

**Pull request closed without merging**
